### ISSUE TITLE
Swim Version in template build.gradle

### ISSUE THREAD

**Issue by ajay-gov** [nstreamio/swim-create#2]
Change the version to 4.1.12, it is currently 4.0.1

**Comment by DobromirM** [comment]
The `4.1.0.12` still shows as a draft in the `swim/swimos` repo https://github.com/swimos/swim/releases 

Is it a stable release?

**Comment by ajay-gov** [comment]
Good catch. It is the latest release, just published it

**Comment by DobromirM** [comment]
That's updated now.
