### ISSUE TITLE
./gradlew call fails

### ISSUE THREAD

**Issue by ajay-gov** [nstreamio/swim-create#3]
Two problems here:

- [x]  `gradlew` and `gradlew.bat` files aren't executable. We should change the mode to executable in the git repo and in the gz package
- [x]  Missing the gradle folders which is invoked from the gradlew script. The template and the gz package should have the gradle folders. You can use the ones from the swimOS/swim repo

**Comment by DobromirM** [comment]
This should now work correctly on *nix systems. There is still a bug with the windows version but I am looking into it.
